var countryData = {
  "AF": {"fullName": "Afghanistan", "coords": [33, 65]},
  "AL": {"fullName": "Albania", "coords": [41, 20]},
  "DZ": {"fullName": "Algeria", "coords": [28, 3]},
  "AO": {"fullName": "Angola", "coords": [-12.5, 18.5]},
  "AR": {"fullName": "Argentina", "coords": [-34, -64]},
  "AM": {"fullName": "Armenia", "coords": [40, 45]},
  "AU": {"fullName": "Australia", "coords": [-27, 133]},
  "AT": {"fullName": "Austria", "coords": [47.3333, 13.3333]},
  "AZ": {"fullName": "Azerbaijan", "coords": [40.5, 47.5]},
  "BS": {"fullName": "Bahamas", "coords": [24.25, -76]},
  "BD": {"fullName": "Bangladesh", "coords": [24, 90]},
  "BY": {"fullName": "Belarus", "coords": [53, 28]},
  "BE": {"fullName": "Belgium", "coords": [50.8333, 4]},
  "BZ": {"fullName": "Belize", "coords": [17.25, -88.75]},
  "BJ": {"fullName": "Benin", "coords": [9.5, 2.25]},
  "BT": {"fullName": "Bhutan", "coords": [27.5, 90.5]},
  "BO": {"fullName": "Bolivia", "coords": [-17, -65]},
  "BA": {"fullName": "Bosnia and Herz.", "coords": [44, 18]},
  "BW": {"fullName": "Botswana", "coords": [-22, 24]},
  "BR": {"fullName": "Brazil", "coords": [-10, -55]},
  "BN": {"fullName": "Brunei", "coords": [4.5, 114.6667]},
  "BG": {"fullName": "Bulgaria", "coords": [43, 25]},
  "BF": {"fullName": "Burkina Faso", "coords": [13, -2]},
  "BI": {"fullName": "Burundi", "coords": [-3.5, 30]},
  "KH": {"fullName": "Cambodia", "coords": [13, 105]},
  "CM": {"fullName": "Cameroon", "coords": [6, 12]},
  "CA": {"fullName": "Canada", "coords": [60, -95]},
  "CF": {"fullName": "Central African Rep.", "coords": [7, 21]},
  "TD": {"fullName": "Chad", "coords": [15, 19]},
  "CL": {"fullName": "Chile", "coords": [-30, -71]},
  "CN": {"fullName": "China", "coords": [35, 105]},
  "CO": {"fullName": "Colombia", "coords": [4, -72]},
  "CG": {"fullName": "Congo", "coords": [-1, 15]},
  "CR": {"fullName": "Costa Rica", "coords": [10, -84]},
  "HR": {"fullName": "Croatia", "coords": [45.1667, 15.5]},
  "CU": {"fullName": "Cuba", "coords": [21.5, -80]},
  "CY": {"fullName": "Cyprus", "coords": [35, 33]},
  "CZ": {"fullName": "Czech Rep.", "coords": [49.75, 15.5]},
  "CI": {"fullName": "Côte d'Ivoire", "coords": [8, -5]},
  "CD": {"fullName": "Dem. Rep. Congo", "coords": [0, 25]},
  "KP": {"fullName": "Dem. Rep. Korea", "coords": [40, 127]},
  "DK": {"fullName": "Denmark", "coords": [56, 10]},
  "DJ": {"fullName": "Djibouti", "coords": [11.5, 43]},
  "DO": {"fullName": "Dominican Rep.", "coords": [19, -70.6667]},
  "EC": {"fullName": "Ecuador", "coords": [-2, -77.5]},
  "EG": {"fullName": "Egypt", "coords": [27, 30]},
  "SV": {"fullName": "El Salvador", "coords": [13.8333, -88.9167]},
  "GQ": {"fullName": "Eq. Guinea", "coords": [2, 10]},
  "ER": {"fullName": "Eritrea", "coords": [15, 39]},
  "EE": {"fullName": "Estonia", "coords": [59, 26]},
  "ET": {"fullName": "Ethiopia", "coords": [8, 38]},
  "FK": {"fullName": "Falkland Is.", "coords": [-51.75, -59]},
  "FJ": {"fullName": "Fiji", "coords": [-18, 175]},
  "FI": {"fullName": "Finland", "coords": [64, 26]},
  "TF": {"fullName": "Fr. S. Antarctic Lands", "coords": [-43, 67]},
  "FR": {"fullName": "France", "coords": [46, 2]},
  "GA": {"fullName": "Gabon", "coords": [-1, 11.75]},
  "GM": {"fullName": "Gambia", "coords": [13.4667, -16.5667]},
  "GE": {"fullName": "Georgia", "coords": [42, 43.5]},
  "DE": {"fullName": "Germany", "coords": [51, 9]},
  "GH": {"fullName": "Ghana", "coords": [8, -2]},
  "GR": {"fullName": "Greece", "coords": [39, 22]},
  "GL": {"fullName": "Greenland", "coords": [72, -40]},
  "GT": {"fullName": "Guatemala", "coords": [15.5, -90.25]},
  "GN": {"fullName": "Guinea", "coords": [11, -10]},
  "GW": {"fullName": "Guinea-Bissau", "coords": [12, -15]},
  "GY": {"fullName": "Guyana", "coords": [5, -59]},
  "HT": {"fullName": "Haiti", "coords": [19, -72.4167]},
  "HN": {"fullName": "Honduras", "coords": [15, -86.5]},
  "HU": {"fullName": "Hungary", "coords": [47, 20]},
  "IS": {"fullName": "Iceland", "coords": [65, -18]},
  "IN": {"fullName": "India", "coords": [20, 77]},
  "ID": {"fullName": "Indonesia", "coords": [-5, 120]},
  "IR": {"fullName": "Iran", "coords": [32, 53]},
  "IQ": {"fullName": "Iraq", "coords": [33, 44]},
  "IE": {"fullName": "Ireland", "coords": [53, -8]},
  "IL": {"fullName": "Israel", "coords": [31.5, 34.75]},
  "IT": {"fullName": "Italy", "coords": [42.8333, 12.8333]},
  "JM": {"fullName": "Jamaica", "coords": [18.25, -77.5]},
  "JP": {"fullName": "Japan", "coords": [36, 138]},
  "JO": {"fullName": "Jordan", "coords": [31, 36]},
  "KZ": {"fullName": "Kazakhstan", "coords": [48, 68]},
  "KE": {"fullName": "Kenya", "coords": [1, 38]},
  "KR": {"fullName": "Korea", "coords": [37, 127.5]},
  "KW": {"fullName": "Kuwait", "coords": [29.3375, 47.6581]},
  "KG": {"fullName": "Kyrgyzstan", "coords": [41, 75]},
  "LA": {"fullName": "Lao PDR", "coords": [18, 105]},
  "LV": {"fullName": "Latvia", "coords": [57, 25]},
  "LB": {"fullName": "Lebanon", "coords": [33.8333, 35.8333]},
  "LS": {"fullName": "Lesotho", "coords": [-29.5, 28.5]},
  "LR": {"fullName": "Liberia", "coords": [6.5, -9.5]},
  "LY": {"fullName": "Libya", "coords": [25, 17]},
  "LT": {"fullName": "Lithuania", "coords": [56, 24]},
  "LU": {"fullName": "Luxembourg", "coords": [49.75, 6.1667]},
  "MK": {"fullName": "Macedonia", "coords": [41.8333, 22]},
  "MG": {"fullName": "Madagascar", "coords": [-20, 47]},
  "MW": {"fullName": "Malawi", "coords": [-13.5, 34]},
  "MY": {"fullName": "Malaysia", "coords": [2.5, 112.5]},
  "ML": {"fullName": "Mali", "coords": [17, -4]},
  "MR": {"fullName": "Mauritania", "coords": [20, -12]},
  "MX": {"fullName": "Mexico", "coords": [23, -102]},
  "MD": {"fullName": "Moldova", "coords": [47, 29]},
  "MN": {"fullName": "Mongolia", "coords": [46, 105]},
  "ME": {"fullName": "Montenegro", "coords": [42, 19]},
  "MA": {"fullName": "Morocco", "coords": [32, -5]},
  "MZ": {"fullName": "Mozamb", "coords": [-18.25, 35]},
  "MM": {"fullName": "Myanmar", "coords": [22, 98]},
  "NA": {"fullName": "Namibia", "coords": [-22, 17]},
  "NP": {"fullName": "Nepal", "coords": [28, 84]},
  "NL": {"fullName": "Netherlands", "coords": [52.5, 5.75]},
  "NC": {"fullName": "New Caledonia", "coords": [-21.5, 165.5]},
  "NZ": {"fullName": "New Zealand", "coords": [-41, 174]},
  "NI": {"fullName": "Nicaragua", "coords": [13, -85]},
  "NE": {"fullName": "Niger", "coords": [16, 8]},
  "NG": {"fullName": "Nigeria", "coords": [10, 8]},
  "NO": {"fullName": "Norway", "coords": [62, 10]},
  "OM": {"fullName": "Oman", "coords": [21, 57]},
  "PK": {"fullName": "Pakistan", "coords": [30, 70]},
  "PS": {"fullName": "Palestine", "coords": [32, 35.25]},
  "PA": {"fullName": "Panama", "coords": [9, -80]},
  "PG": {"fullName": "Papua New Guinea", "coords": [-6, 147]},
  "PY": {"fullName": "Paraguay", "coords": [-23, -58]},
  "PE": {"fullName": "Peru", "coords": [-10, -76]},
  "PH": {"fullName": "Philippines", "coords": [13, 122]},
  "PL": {"fullName": "Poland", "coords": [52, 20]},
  "PT": {"fullName": "Portugal", "coords": [39.5, -8]},
  "PR": {"fullName": "Puerto Rico", "coords": [18.25, -66.5]},
  "QA": {"fullName": "Qatar", "coords": [25.5, 51.25]},
  "RO": {"fullName": "Romania", "coords": [46, 25]},
  "RU": {"fullName": "Russia", "coords": [60, 100]},
  "RW": {"fullName": "Rwanda", "coords": [-2, 30]},
  "SS": {
    "fullName": "S. Sudan"
  },
  "SA": {"fullName": "Saudi Arabia", "coords": [25, 45]},
  "SN": {"fullName": "Senegal", "coords": [14, -14]},
  "RS": {"fullName": "Serbia", "coords": [44, 21]},
  "SL": {"fullName": "Sierra Leone", "coords": [8.5, -11.5]},
  "SK": {"fullName": "Slovakia", "coords": [48.6667, 19.5]},
  "SI": {"fullName": "Slovenia", "coords": [46, 15]},
  "SB": {"fullName": "Solomon Is.", "coords": [-8, 159]},
  "SO": {"fullName": "Somalia", "coords": [10, 49]},
  "ZA": {"fullName": "South Africa", "coords": [-29, 24]},
  "ES": {"fullName": "Spain", "coords": [40, -4]},
  "LK": {"fullName": "Sri Lanka", "coords": [7, 81]},
  "SD": {"fullName": "Sudan", "coords": [15, 30]},
  "SR": {"fullName": "Suriname", "coords": [4, -56]},
  "SZ": {"fullName": "Swaziland", "coords": [-26.5, 31.5]},
  "SE": {"fullName": "Sweden", "coords": [62, 15]},
  "CH": {"fullName": "Switzerland", "coords": [47, 8]},
  "SY": {"fullName": "Syria", "coords": [35, 38]},
  "TW": {"fullName": "Taiwan", "coords": [23.5, 121]},
  "TJ": {"fullName": "Tajikistan", "coords": [39, 71]},
  "TZ": {"fullName": "Tanzania", "coords": [-6, 35]},
  "TH": {"fullName": "Thailand", "coords": [15, 100]},
  "TL": {
    "fullName": "Timor-Leste"
  },
  "TG": {"fullName": "Togo", "coords": [8, 1.1667]},
  "TT": {"fullName": "Trinidad and Tobago", "coords": [11, -61]},
  "TN": {"fullName": "Tunisia", "coords": [34, 9]},
  "TR": {"fullName": "Turkey", "coords": [39, 35]},
  "TM": {"fullName": "Turkmenistan", "coords": [40, 60]},
  "UG": {"fullName": "Uganda", "coords": [1, 32]},
  "UA": {"fullName": "Ukraine", "coords": [49, 32]},
  "AE": {"fullName": "United Arab Emirates", "coords": [24, 54]},
  "GB": {"fullName": "United Kingdom", "coords": [54, -2]},
  "US": {"fullName": "United States", "coords": [38, -97]},
  "UY": {"fullName": "Uruguay", "coords": [-33, -56]},
  "UZ": {"fullName": "Uzbekistan", "coords": [41, 64]},
  "VU": {"fullName": "Vanuatu", "coords": [-16, 167]},
  "VE": {"fullName": "Venezuela", "coords": [8, -66]},
  "VN": {"fullName": "Vietnam", "coords": [16, 106]},
  "EH": {"fullName": "W. Sahara", "coords": [24.5, -13]},
  "YE": {"fullName": "Yemen", "coords": [15, 48]},
  "ZM": {"fullName": "Zambia", "coords": [-15, 30]},
  "ZW": {"fullName": "Zimbabwe", "coords": [-20, 30]}
}